import type { SkillCategory } from "@veyro/contracts";

export const SKILL_LABELS: Record<SkillCategory, string> = {
  ELECTRICIAN: "Electrician",
  PLUMBER: "Plumber",
  CARPENTER: "Carpenter",
  PAINTER: "Painter",
  WELDER: "Welder",
  AC_TECHNICIAN: "AC Technician",
  GENERATOR_TECHNICIAN: "Generator Technician",
  SOLAR_TECHNICIAN: "Solar Technician",
  CCTV_INSTALLER: "CCTV Installer",
  AUTO_MECHANIC: "Auto Mechanic",
  POP_INSTALLER: "POP Installer",
  TILER: "Tiler",
  FURNITURE_MAKER: "Furniture Maker",
  INTERIOR_DECORATOR: "Interior Decorator",
  CLEANER: "Cleaner",
  PHONE_REPAIR_TECHNICIAN: "Phone Repair Technician",
  COMPUTER_TECHNICIAN: "Computer Technician",
  REFRIGERATOR_TECHNICIAN: "Refrigerator Technician",
  BOREHOLE_TECHNICIAN: "Borehole Technician",
  ALUMINIUM_FABRICATOR: "Aluminium Fabricator",
  BRICKLAYER: "Bricklayer",
  MASON: "Mason",
  ROOFER: "Roofer",
  CEILING_INSTALLER: "Ceiling Installer",
  UPHOLSTERER: "Upholsterer",
  BARBER: "Barber",
  HAIR_STYLIST: "Hair Stylist",
  MAKEUP_ARTIST: "Makeup Artist",
  TAILOR: "Tailor / Fashion Designer",
  LAUNDRY_SERVICE_PROVIDER: "Laundry Service Provider",
  PHOTOGRAPHER: "Photographer",
  VIDEOGRAPHER: "Videographer",
  EVENT_DECORATOR: "Event Decorator",
  CATERER: "Caterer",
  BAKER: "Baker",
  PEST_CONTROL_SPECIALIST: "Pest Control Specialist",
  LOCKSMITH: "Locksmith",
  VULCANIZER: "Vulcanizer",
  PANEL_BEATER: "Panel Beater",
  GATE_AUTOMATION_TECHNICIAN: "Gate Automation Technician",
};

export const SKILL_CATEGORIES = Object.keys(SKILL_LABELS) as SkillCategory[];

export const EXPERIENCE_LABELS: Record<string, string> = {
  "0-2": "0-2 yrs",
  "3-5": "3-5 yrs",
  "6-10": "6-10 yrs",
  "10+": "10+ yrs",
};
